// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLxujZJsBfDKUMK09BFOe9eAUtMRRHWmA',
    appId: '1:699099668215:web:4a1729676ff8218cb67df2',
    messagingSenderId: '699099668215',
    projectId: 'flutter-project-85100',
    authDomain: 'flutter-project-85100.firebaseapp.com',
    storageBucket: 'flutter-project-85100.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARgaViTvjd-NDNnsLr1VJz7M_yOk0YZ9Y',
    appId: '1:699099668215:android:98994273ac869b98b67df2',
    messagingSenderId: '699099668215',
    projectId: 'flutter-project-85100',
    storageBucket: 'flutter-project-85100.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgdi_7j5lnp7-lBWm4zyTLmbW_D_UqJvE',
    appId: '1:699099668215:ios:8cd1d5c81a273ac1b67df2',
    messagingSenderId: '699099668215',
    projectId: 'flutter-project-85100',
    storageBucket: 'flutter-project-85100.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgdi_7j5lnp7-lBWm4zyTLmbW_D_UqJvE',
    appId: '1:699099668215:ios:8cd1d5c81a273ac1b67df2',
    messagingSenderId: '699099668215',
    projectId: 'flutter-project-85100',
    storageBucket: 'flutter-project-85100.appspot.com',
    iosBundleId: 'com.example.firebase',
  );
}
